abbreviations:
  ВГП: водогазопроводная
  ВЧШГ: чугун
  оц: оцинкованный
  фл: фланцевый
  фланц: фланцевый
  э/с: электросварная
context_insignificant:
- base: Труба стальная водогазопроводная оцинкованная
  drop: на грувлоках
param_words:
- ру
- pn
- нр
- np
- kvs
- kv
- бар
- па
- атм
- тмакс
- макс
- мин
- max
- min
- град
stopwords:
- для
- из
- с
- со
- на
- по
- в
- во
- и
- не
- или
- к
- у
- от
- при
- за
- что
- это
- как
- так
- об
- про
- под
- мм
- ду
- типа
- тип
- размер
- новый
- отечественный
structural_words:
- завод
- изготовитель
- производитель
- марка
- бренд
- гост
- ту
